# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  in_progress_fortune: false
  poem: false
  review_status: true

  auto_review:
    enabled: true
    drafts: false
    ignore_usernames:
      - "dependabot[bot]"

  tools:
    github-checks:
      enabled: true
      timeout_ms: 900000

chat:
  auto_reply: true
